### ISSUE TITLE
RU14 - Integrar el código de Cobertura

### ISSUE THREAD

**Issue by FelipeRubilar** [Ciclop/Terasology#1]
Requisitos de Usuario
Franco Pino y Felipe Rubilar

Deben integrarse las funciones y capacidades de Cobertura a Terasology, de manera de poder luego usarlas para el coloreo de mapas. 
- [X] Iteracion 1
  - [X] RS50: Identificar input/output de Cobertura #80 
  - [X] RS51: Implementar interfaz de comunicacion entre Terasology y Cobertura #81 
- [X] Iteracion 2  
  - [X] RS52: Implementar método que envíe un Input hacia Cobertura #82 
  - [X] RS53: Implementar método que reciba el output de Cobertura #83

**Comment by FelipeRubilar** [comment]
- El código y las librerías de Cobertura fueron agregadas al módulo del mismo nombre. (Closes #80, #81)
- Se crea la clase CoberturaCommand para implementar los métodos que ejecutan el análisis (Closes #82) 
- Se crea la clase XMLParser para interpretar el reporte generado por Cobertura (Closes #83)
