### ISSUE TITLE
RU24 - Implementar modo fly

### ISSUE THREAD

**Issue by criparra** [Ciclop/Terasology#10]
Requisitos de Usuario
Cristian Parra
- [x] Iteración 1
  - [x] Investigación del modo Fly de modo de obtener las clases relacionadas con el movimiento del personaje, así como la clase relacionada con los botones del juego. #75
- [x] Iteración 2  
  - [x] RS21: Modificación del movimiento del personaje en el modo Fly #49 
  - [x] RS25: El personaje debe moverse por medio del teclado #53 
  - [x] RS26: Implementación de un botón para el llamado a modo Fly #54 
- [x] Iteración 3  
  - [x] RS22: Modificación de la gravedad interna de Terasology #50 
  - [x] RS23: Guardar la posición inicial desde la que se comenzó a volar #51 
  - [x] RS24: Volver a la posición inicial desde la que se empezó a volar #52

**Comment by criparra** [comment]
Se ha logrado finalizar con los requisitos de usuario iniciales, implementando todo lo pedido.
