### ISSUE TITLE
RU26 - Volver a la superficie al desactivar modo Fly

### ISSUE THREAD

**Issue by criparra** [Ciclop/Terasology#12]
Requisitos de Usuario
Cristian Parra
- [x] Iteracion 1
  - [x] #75 Investigación del modo Fly de modo de obtener las clases relacionadas con el movimiento del personaje, así como la clase relacionada con los botones del juego.
- [x] Iteracion 2 y 3
  - [x] RS23: Guardar la posición inicial desde la que se comenzó a volar #51 
  - [x] RS24: Volver a la posición inicial desde la que se empezó a volar #52

**Comment by criparra** [comment]
Se ha realizado la acción de que el personaje vuelva a la posición desde la cual comenzó a volar.
