### ISSUE TITLE
RU27 - Movimientos proporcionales al tamaño del mapa en modo Fly

### ISSUE THREAD

**Issue by criparra** [Ciclop/Terasology#13]
Requisitos de Usuario
Cristian Parra
- [x] Iteracion 1
  - [x] #75 Investigación del modo Fly de modo de obtener las clases relacionadas con el movimiento del personaje, así como la clase relacionada con los botones del juego.
- [x] Iteracion 2 y 3
  - [x] RS21: Modificación del movimiento del personaje en el modo Fly #49 
  - [x] RS22: Modificación de la gravedad interna de Terasology #50 
  - [x] RS25: El personaje debe moverse por medio del teclado #53

**Comment by criparra** [comment]
El personaje puede moverse a través del mapa por medio de las teclas del teclado y del mouse.
