### ISSUE TITLE
RU17 - Botón Cobertura

### ISSUE THREAD

**Issue by FelipeRubilar** [Ciclop/Terasology#14]
Requisitos de Usuario
Franco Pino y Felipe Rubilar
- [X] Iteracion 1
  - [X] RS10: Ejecutar análisis y generar cambios del coloreo desde la consola de Terasology #38 
- [X] Iteracion 2  
  - [X] RS11: Agregar submenú de análisis/coloreo al menú de pausa #39
  - [X] RS30: Agregar opción Cobertura al submenú de análisis del menú de Pausa #58 
- [ ] Iteración 3
  - [ ] RS31: Agregar herramienta en el juego que genere los cambios producidos por el análisis de Cobertura. #59

**Comment by FelipeRubilar** [comment]
- Se implementa el método CoberturaAnalysis, que ejecuta el análisis sobre los archivos especificados y genera el reporte asociado. Hasta el momento sólo se imprimen los resultados en consola; falta implementar el coloreo.
- Se agrega el submenú de coloreo al menú de pausa. Falta implementar la funcionalidad de cada uno de los botones.
