### ISSUE TITLE
RU20 - Integrar Cobertura

### ISSUE THREAD

**Issue by FelipeRubilar** [Ciclop/Terasology#19]
Requisitos de Usuario
Franco Pino y Felipe Rubilar

En Terasology, debe haber forma de llamar y hacer uso de las capacidades de Cobertura, así como una forma de generar diseños de coloreo que dependan de los resultados de estas funciones.
- [X] Iteracion 1
  - [X] RS52: Implementar interfaz para enviar input (código) a ser analizado por Cobertura. #82 
  - [X] RS53: Implementar interfaz para recibir y almacenar output (análisis) de Cobertura, para su procesamiento. #83 
- [X] Iteracion 2  
  - [X] RS57: Asignar resultado de métrica a una representación en el juego por medio de coloreo de bloques. #87 
  - [X] RS58: Aplicar coloreo de bloques individuales (recibir bloque, devolver color). #88

**Comment by FelipeRubilar** [comment]
- Se implementa el comando CoberturaAnalysis para ejecutar el analisis sobre los archivos especificados
- Se crea la clase XMLParser para interpretar los reportes generados.

**Comment by FelipeRubilar** [comment]
- Se implementan los bloques "Coloring:morado", "Coloring:rojo", "Coloring:naranjo", "Coloring:amarillo", "Coloring:lime", "Coloring:verde", "Coloring:azul" en el módulo Coloring, para ser utilizados por el coloreo como representación de los resultados de los análisis.
- Se implementa el método getColor(String class) en CoberturaCommand, que devuelve el bloque asociado al valor del resultado del análisis en la clase especificada.
