### ISSUE TITLE
RU5 - Coloreo PMD instantáneo

### ISSUE THREAD

**Issue by elarielcl** [Ciclop/Terasology#2]
Requisitos de Usuario
Manuel Cáceres Reyes y Joaquín Romero Munizaga
- [x] Iteración 1
  - [x] RS21: Coloreo PMD funcional #55 
- [x] Iteración 2  
  - [x] RS16: Ventana de espera para coloreo #44 
- [x] Iteración 3  
  - [x] RS44: Optimizar tiempo de ejecución de coloreo PMD #77 
  - [x] RS45: Si es que ,RS44 fue efectivo, eliminar ventana de espera #78

**Comment by joromero** [comment]
Puesto que el análisis y el coloreo fueron separados en dos comandos no se hace necesario mostrar la ventana de espera.

**Comment by joromero** [comment]
Cerrando el requisito pues se encuentra todo implementado.
