### ISSUE TITLE
RU10 - Colorear con información entregada por CheckStyle

### ISSUE THREAD

**Issue by emoreno-94** [Ciclop/Terasology#20]
Requisitos de Usuario
Edward Moreno y Sebastián Ormeño
- [x] Iteración 1
  - [x]  RS13: Colorear un bloque desde consola de Terasology #41 
  - [x]  RS14: Colorear un conjunto de bloques desde consola de Terasology #42
- [x] Iteración 2  
  - [x] RS15: Colorear ciudades estilo CodeCity #43
- [x] Iteración 3
  - ~~RS35 : Implementar primera métrica de coloreo CheckStyle #63~~
  - ~~RS36 : Implementar segunda métrica de coloreo CheckStyle #64~~
  - [x] Implementar metricas CheckStyle #127
