### ISSUE TITLE
RU12 - Botón CheckStyle

### ISSUE THREAD

**Issue by emoreno-94** [Ciclop/Terasology#23]
Requisitos de Software

Edward Moreno y Sebastián Ormeño
- [x] Iteracion 1
  - [x] RS10: Ejecutar análisis y generar cambios del coloreo desde la consola de Terasology #38 
- [x] Iteracion 2  
  - [x] RS11: Agregar submenú de análisis/coloreo al menú de pausa #39
  - [x] RS37: Agregar opción CheckStyle al submenú de análisis del menú de Pausa #65 
- [ ] Iteración 3
  - [ ] RS38: Agregar herramienta CheckStyle #66

**Comment by seanorar** [comment]
Se creo el comando de consola paintWithCheckStyle el cual entregandole como parámetro la ruta, la métrica y el valor máximo, colorea la ciudad dependiendo del resultado del ánalisis

**Comment by seanorar** [comment]
Se asigno este comando a los distintos botones del submenu de Coloreo, de esta manera al presionar las opciones se completan los parametros restantes para poder ejecutar el coloreo desde el submenu y ver el resultado al volver al juego.
