### ISSUE TITLE
RU13 - Coloreo CheckStyle instantáneo

### ISSUE THREAD

**Issue by emoreno-94** [Ciclop/Terasology#25]
Requisitos de Software
Edward Moreno y Sebastián Ormeño
- [x] Iteración 1
  - [x] RS33: Implementar integración CheckStyle #61
- [x] Iteración 2  
  - [x] RS16: Ventana de espera para coloreo #44
- [x] Iteración 3
  - [x] RS34 - Realizar coloreo y análisis según CheckStyle de manera instantánea #62

**Comment by emoreno-94** [comment]
El análisis se ejecuta en un thread aparte desde commit bac33661585e21b5d5645576294dd6a4ae535681, esto para que no interfiera en la ejecución del juego

**Comment by seanorar** [comment]
En un principio se intento realizar el analisis y el coloreo en un thread, pero al intentarlo este arrojaba un error que indicaba que no se podia colocar nuevo bloques en el thread.
De esta manera se decidio separar los trabajos, el analisis es realizado en un thread, y su resultado es recibido y a partir de este se genera el coloreo en el proceso principal.

**Comment by seanorar** [comment]
Como el analisis no es instantaneo, se coloco un botón que indica el estado del proceso, de esta manera el usuario puede saber el estado del coloreo mientras esto no interfiere en el uso del juego.
