### ISSUE TITLE
RU33 - Botón PMD

### ISSUE THREAD

**Issue by elarielcl** [Ciclop/Terasology#26]
Requisitos de Usuario
Manuel Cáceres Reyes y Joaquín Romero Munizaga
- [x] Iteración 1
  - [x] RS10: Ejecutar análisis y generar cambios del coloreo desde la consola de Terasology #38 
- [x] Iteración 2  
  - [x] RS11: Agregar submenú de análisis/coloreo al menú de pausa #39
  - [x] RS17: Agregar opción PMD al submenú de análisis del menú de pausa #45 
- [ ] Iteración 3
  - [ ] RS12: Agregar nueva herramienta sin funcionalidad #40 
  - [ ] RS18: Agregar herramienta PMD #46
