### ISSUE TITLE
RU35 - Colorear con información entregada por PMD

### ISSUE THREAD

**Issue by elarielcl** [Ciclop/Terasology#28]
Requisitos de Usuario
Manuel Cáceres Reyes y Joaquín Romero Munizaga
- [x] Iteración 1
  - [x] RS13: Colorear un bloque desde consola de Terasology #41 
  - [x] RS14: Colorear un conjunto de bloques desde consola de Terasology #42 
- [x] Iteración 2  
  - [x] RS15: Colorear ciudades estilo CodeCity #43
- [x] Iteración 3  
  - [x] RS23: Construir coloreo PMD #57
