### ISSUE TITLE
RU3 - Obtención de métricas de un proyecto utilizando JEdit

### ISSUE THREAD

**Issue by fdns** [Ciclop/Terasology#7]
Requisitos de Usuario
Ednar Echeverría y Felipe Espinoza
- [x] Iteracion 1
  - [x] RS4: Socket conexion JEdit. #32
  - [x] RS5: Estructura de almacenamiento JEdit. #33
  - [x] RS6: Método de generación mapa con datos JEdit. #34
  - [x] RS8: Método para iniciar la actividad del socket. #36
- [x] Iteracion 2  
  - [x] RS7: Método para guardar los datos obtenidos de JEdit. #35
  - [x] RS9: Método para iniciar el guardado de datos. #37
