### ISSUE TITLE
RU22 - Llamar a JEdit desde Terasology

### ISSUE THREAD

**Issue by Phfollert** [Ciclop/Terasology#71]
Requisitos de Usuario
Patricio Huepe
- [x] Iteración 1
  - [x] RS39: Método para abrir JEdit en una línea de código determinada #68
  - [x] RS41: Crear bloque que guarde información relacionada al código generador de estructura. #69
- [x] Iteración 2
  - [x] RS59: El llamado consecutivo a jedit desde Terasology no debe abrirlo más de una vez #89

**Comment by Phfollert** [comment]
Requisito de usuario cumplido
