### ISSUE TITLE
RU15 - Colorear con información entregada por Cobertura

### ISSUE THREAD

**Issue by FelipeRubilar** [Ciclop/Terasology#8]
Requisitos de Usuario
Franco Pino y Felipe Rubilar
- [X] Iteración 1
  - [X] RS13: Colorear un bloque desde consola de Terasology #41 
  - [X] RS14: Colorear un conjunto de bloques desde consola de Terasology #42  
- [X] Iteración 2  
  - [X] RS15: Colorear ciudades estilo CodeCity #43 
- [X] Iteración 3:
  - [X] RS54: Implementar método de coloreo Cobertura para un mapa CodeCity completo. #84
